name: ree_gig
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  #Form Validator
  form_field_validator: ^1.1.0
  #Fire Base
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  get_storage:
  #SQL Database Storage
  sqflite: ^2.0.2+1
  #Google Maps
  google_maps_flutter: ^2.1.6
  #Google Fonts
  google_fonts: ^3.0.1
  #For Shared Preferences
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  #Flutter toasts
  fluttertoast: ^8.0.9
  #Flutter vibrate
  flutter_vibrate: ^1.3.0
  #Flutter pi charts
  pie_chart: ^5.3.1



  #internet connectivity checker
#  internet_connection_checker: ^0.0.1+4
  #geo locator
  geolocator: ^8.2.1
  geocoding: ^2.0.4



  image_picker: ^0.8.5
  firebase_storage: ^10.2.12
  velocity_x: ^3.4.0
  introduction_screen: ^3.0.2
  lottie:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #splash Screen
  flutter_native_splash:

flutter_native_splash:
  color: "#ffffff"
  image: logos/reegigLogo.png


flutter:

  uses-material-design: true

  assets:
    - images/
    - animations/
    - icons/
    - logos/
    - abstracts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-ExtraLight.ttf
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
